name: Bug Report
description: Report a bug or issue with SwiftlyS2
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: swiftly-version
    attributes:
      label: SwiftlyS2 Version
      description: What version of SwiftlyS2 are you running?
      placeholder: e.g., v1.0.0, latest commit hash
    validations:
      required: true

  - type: dropdown
    id: game
    attributes:
      label: Game
      description: Which Source 2 game are you using?
      options:
        - Counter-Strike 2
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load plugin '...'
        2. Execute command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Console Output
      description: If applicable, add console output or log files to help explain your problem.
      render: text
      placeholder: Paste your logs here...

  - type: textarea
    id: plugin-info
    attributes:
      label: Plugin Information
      description: If this is related to a specific plugin, provide details about it.
      placeholder: |
        - Plugin name: 
        - Plugin version: 
        - Plugin source: 

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
