name: Build

on: [workflow_dispatch]

env:
  XMAKE_ROOT: y

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Fix LibGit2Sharp
      run: |
        git config --global --add safe.directory '*'
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.3.x'
    - name: Determine Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v4.1.0
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Build
      run: |
        xmake build
      env:
        GITHUB_SHA: ${{ steps.gitversion.outputs.sha }}
        SWIFTLY_VERSION: ${{ steps.gitversion.outputs.fullSemVer }}
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swiftlys2_linux
        path: build/package/addons