name: Build

on: [push, workflow_dispatch]

env:
  XMAKE_ROOT: y

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}
      semVer: ${{ steps.version_step.outputs.semVer }}
      informationalVersion: ${{ steps.version_step.outputs.informationalVersion }}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.3.x'
    - name: Determine Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v4.1.0
  managed:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build managed
      run: |
        cd managed
        dotnet build -c Release -p:Version=${{ needs.versioning.outputs.fullSemVer }} -p:InformationalVersion=${{ needs.versioning.outputs.informationalVersion }} -p:FileVersion=${{ needs.versioning.outputs.semVer }}
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swiftlys2_managed
        path: managed/build/Release
  linux_core:
    needs: versioning
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt install libreadline-dev
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        build-cache: true
    - name: Restore build cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          build
        key: ${{ runner.os }}-build
    - name: Build
      run: |
        xmake f --cc=gcc-14 --cxx=g++-14 -y
        xmake build -y
      env:
        SWIFTLY_VERSION: ${{ needs.versioning.outputs.fullSemVer }}
    - name: Save cache
      id: save-cache
      uses: actions/cache/save@v4
      with:
        path: |
          build
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swiftlys2_linux
        path: build/package/addons

  windows_core:
    needs: versioning
    runs-on: windows-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        build-cache: true
    - name: Restore build cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          build
        key: ${{ runner.os }}-build
    - name: Build
      run: |
        xmake f --ccache=y
        xmake build -y
      env:
        SWIFTLY_VERSION: ${{ needs.versioning.outputs.fullSemVer }}
    - name: Save cache
      id: save-cache
      uses: actions/cache/save@v4
      with:
        path: |
          build
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swiftlys2_windows
        path: build/package/addons
    - name: Upload PDB as artifact
      uses: actions/upload-artifact@v4
      with:
        name: swiftlys2_windows_pdb
        path: build/windows/x64/release/swiftlys2.pdb

  packaging:
    needs: [versioning, linux_core, windows_core, managed]
    runs-on: ubuntu-latest
    env:
      LINUX_FOLDER: swiftlys2-linux-${{ needs.versioning.outputs.fullSemVer }}
      WINDOWS_FOLDER: swiftlys2-windows-${{ needs.versioning.outputs.fullSemVer }}
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: swiftlys2_linux
        path: ./${{ env.LINUX_FOLDER }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: swiftlys2_windows
        path: ./${{ env.WINDOWS_FOLDER }}
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: swiftlys2_managed
        path: ./managed
    - name: Download runtimes
      run: |
        mkdir -p ./linux-runtimes
        cd ./linux-runtimes
        wget https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.20/dotnet-runtime-8.0.20-linux-x64.tar.gz
        mkdir -p content
        tar -xzf dotnet-runtime-8.0.20-linux-x64.tar.gz -C content
        cd ..
        mkdir -p ./windows-runtimes
        cd ./windows-runtimes
        wget https://builds.dotnet.microsoft.com/dotnet/Runtime/8.0.20/dotnet-runtime-8.0.20-win-x64.zip
        unzip dotnet-runtime-8.0.20-win-x64.zip -d content
        cd ..
      
    - name: Create package
      run: |
        ls -la ./managed
        cp -r managed/SwiftlyS2 ${{ env.LINUX_FOLDER }}/swiftlys2/bin/managed
        cp -r managed/SwiftlyS2 ${{ env.WINDOWS_FOLDER }}/swiftlys2/bin/managed

        cp -r ${{ env.LINUX_FOLDER }}/ ${{ env.LINUX_FOLDER }}-with-runtimes/
        cp -r ${{ env.WINDOWS_FOLDER }}/ ${{ env.WINDOWS_FOLDER }}-with-runtimes/

        cp -r linux-runtimes/content/ ${{ env.LINUX_FOLDER }}-with-runtimes/swiftlys2/bin/managed/dotnet
        cp -r windows-runtimes/content/ ${{ env.WINDOWS_FOLDER }}-with-runtimes/swiftlys2/bin/managed/dotnet

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: swiftlys2-package-${{ needs.versioning.outputs.fullSemVer }}
        path: |
          ${{ env.LINUX_FOLDER }}
          ${{ env.WINDOWS_FOLDER }}
          ${{ env.LINUX_FOLDER }}-with-runtimes
          ${{ env.WINDOWS_FOLDER }}-with-runtimes